# Generated by Django 3.0.2 on 2020-02-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='none', max_length=100)),
                ('lastname', models.CharField(default='none', max_length=100)),
                ('country', models.CharField(default='bf', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('operator', models.CharField(default=' ', max_length=100)),
                ('acc_type', models.CharField(default='normal', max_length=100)),
                ('acc_state', models.CharField(default='al', max_length=100)),
                ('acc_fees', models.CharField(default='notPaid', max_length=100)),
                ('id_picture', models.ImageField(default='ligdi/static/ligdi/ids/default.jpg', upload_to='ligdi/static/ligdi/ids')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('pack_name', models.CharField(default='none', max_length=100, primary_key=True, serialize=False)),
                ('pack_pos_fee', models.IntegerField(default=0)),
                ('pack_pos_amount', models.IntegerField(default=0)),
                ('pack_pay_tot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_date', models.DateField()),
                ('pos_duration', models.DateField()),
                ('pos_fee_state', models.BooleanField(default=False)),
                ('pos_state', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Account')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Pack')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('id_number', models.CharField(default='B', max_length=100)),
                ('a_state', models.CharField(default='notFill', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_amount', models.IntegerField(default=0)),
                ('ret_state', models.BooleanField(default=False)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.IntegerField(default=0)),
                ('pay_state', models.BooleanField(default=False)),
                ('pay_date', models.DateField()),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Retour')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligdi.User'),
        ),
    ]
