# Generated by Django 3.0.2 on 2020-02-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_duration',
        ),
    ]
