# Generated by Django 3.0.2 on 2020-02-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0002_remove_position_pos_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_picture',
            field=models.ImageField(default='', upload_to='ligdi/static/ligdi/ids'),
        ),
    ]
