# Generated by Django 3.0.2 on 2020-02-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0004_auto_20200213_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='retour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Retour'),
        ),
    ]
