# Generated by Django 3.0.2 on 2020-02-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0005_auto_20200214_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_fee_state',
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vers_date', models.DateField()),
                ('vers_amount', models.IntegerField()),
                ('vers_compte', models.CharField(default='', max_length=100)),
                ('vers_num', models.CharField(default='', max_length=100)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Position')),
            ],
        ),
    ]
