# Generated by Django 3.0.2 on 2020-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0006_auto_20200214_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='vers_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='versement',
            name='vers_amount',
            field=models.IntegerField(default=0),
        ),
    ]
