# Generated by Django 3.0.2 on 2020-02-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0007_auto_20200215_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versement',
            old_name='vers_conf',
            new_name='vers_state',
        ),
        migrations.RemoveField(
            model_name='position',
            name='pos_state',
        ),
    ]
