# Generated by Django 3.0.2 on 2020-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0010_auto_20200216_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='vers_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='versement',
            name='vers_conf_admin',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
