# Generated by Django 3.0.2 on 2020-02-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0012_versement_vers_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versement',
            name='vers_conf',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='vers_conf_admin',
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_date', models.DateField()),
                ('conf_state', models.BooleanField(default=False)),
                ('conf_admin', models.CharField(default=' ', max_length=100)),
                ('versement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligdi.Versement')),
            ],
        ),
    ]
