# Generated by Django 3.0.2 on 2020-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0013_auto_20200216_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='pay_trans_num',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
