# Generated by Django 3.0.2 on 2020-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0014_payement_pay_trans_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pos_en_cour',
            field=models.BooleanField(default=False),
        ),
    ]
