# Generated by Django 3.0.2 on 2020-02-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0015_account_pos_en_cour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='retour',
        ),
        migrations.AddField(
            model_name='payement',
            name='versement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ligdi.Versement'),
            preserve_default=False,
        ),
    ]
