# Generated by Django 3.0.2 on 2020-02-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0017_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='fees_num',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fees',
            name='fees_tel',
            field=models.IntegerField(default=0),
        ),
    ]
