# Generated by Django 3.0.2 on 2020-02-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0018_auto_20200217_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retour',
            name='ret_state',
        ),
    ]
