# Generated by Django 3.0.2 on 2020-02-17 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0019_remove_retour_ret_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='retour',
            name='ret_date_max',
            field=models.DateField(default=datetime.datetime(2020, 2, 17, 18, 8, 54, 4007, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
