# Generated by Django 3.0.2 on 2020-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0021_auto_20200217_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ges_username', models.CharField(default='', max_length=100)),
                ('ges_password', models.CharField(default='', max_length=100)),
                ('ges_firtname', models.CharField(max_length=100)),
                ('ges_lastname', models.CharField(max_length=100)),
                ('ges_phone', models.IntegerField(max_length=100)),
                ('ges_email', models.CharField(max_length=100)),
                ('ges_is_active', models.BooleanField(default=True)),
                ('ges_las_log', models.DateField()),
                ('ges_conf_frai', models.BooleanField(default=False)),
                ('ges_conf_vers', models.BooleanField(default=False)),
                ('ges_conf_pay', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='fees',
            name='fees_tel',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
