# Generated by Django 3.0.2 on 2020-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligdi', '0022_auto_20200217_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionnaire',
            name='ges_phone',
            field=models.IntegerField(),
        ),
    ]
